### ISSUE TITLE
데이터셋 및 모델 정보 문의

### ISSUE THREAD

**Issue by InhyeokYoo** [BM-K/KoIR#1]
안녕하세요. 잘 보고 갑니다.

다름아니라 README에는 네이버지식인 데이터셋을 사용하셨다고 하는데, 혹시 원본 출처를 밝혀주실 수 있으실까요?
찾아보니 https://zenodo.org/records/46018 가 나오는데, 이게 맞는지 확인하고 싶어서요.
그리고 negative sample은 DPR와 비슷하게 BM25로 뽑으신걸까요?

그리고 사용하신 모델은 어떤걸까요? 그냥 KoIR이라고만 되어있는데 직접 설계하신 모델일까요?

감사합니다.

**Comment by BM-K** [comment]
@InhyeokYoo 안녕하세요.

1. 데이터셋 원본 출처

- 네, 링크하신 데이터셋을 파싱해서 사용했습니다.

2. Negative sample 

- Hard negative sample의 경우 BM25가 아닌 지식인 내의 질문과 이에 대한 답변들 중 채택되지 못한 답변을 random sampling하여 구축한 것으로 기억합니다.

3. 사용 모델 
 
- [SimCSE](https://arxiv.org/abs/2104.08821)와 유사한 방식으로 설계하였습니다. 1개의 positive sample과 1개의 hard negative sample 그리고 batch-2 개의 negative sample을 두고 question과 positive sample의 cosine similarity 값이 높아지도록 loss를 설계하여 학습했습니다.

**Comment by InhyeokYoo** [comment]
답변 감사드립니다.
